package models.food;

/**
 * Represents a category that each {@link Food} belongs to.
 *
 * @author Stefan Fritzon, Lisa Snall, Fredrik Kindstrom
 */
public enum Category {
    PULSES_VEGETABLES(TopCategory.PULSES_AND_NUTS), OTHER_FRUITS(TopCategory.FRUITS),
    CANNED_FRUITS(TopCategory.FRUITS), JUICES(TopCategory.FRUITS), JUICE_DRINKS(TopCategory.FRUITS),
    FISH_PRODUCTS(TopCategory.FISH), CITRUS_FRUITS(TopCategory.FRUITS),
    MALACEOUS_FRUITS(TopCategory.FRUITS), LEAF_VEGETABLES(TopCategory.VEGETABLES),
    FRUIT_VEGETABLES(TopCategory.VEGETABLES), ROOT_VEGETABLES_AND_TUBERS(TopCategory.VEGETABLES),
    OILS(TopCategory.FAT), PORK(TopCategory.MEAT), FATS_FOR_COOKING_AND_INDUSTRIA(TopCategory.FAT),
    MISCELLANEOUS_INGREDIENTS(TopCategory.OTHER_INGREDIENTS), SAUSAGES(TopCategory.MEAT),
    CANNED_VEGETABLES(TopCategory.VEGETABLES), BERRIES(TopCategory.FRUITS), MILK(TopCategory.MILK),
    DRIED_HERBS(TopCategory.SPICES), CRUSTACEANS_AND_MOLLUSCS(TopCategory.FISH),
    CHEESE(TopCategory.MILK), BEEF(TopCategory.MEAT), OFFAL(TopCategory.MEAT),
    CABBAGES(TopCategory.VEGETABLES), OTHER_GRAINS(TopCategory.CEREALS), FISH(TopCategory.FISH),
    MEAT_PRODUCTS(TopCategory.MEAT), BIRDS(TopCategory.MEAT),
    INFANT_FORMULAS_AND_HUMAN_MILK(TopCategory.PRODUCTS_FOR_SPECIAL_NUTRITION),
    COFFEE(TopCategory.BEVERAGES), NUTS_AND_SEEDS(TopCategory.PULSES_AND_NUTS),
    EDIBLE_FUNGI(TopCategory.VEGETABLES), CHOCOLATE(TopCategory.SUGAR_AND_CONFECTIONERY),
    OTHER_ALCOHOLIC_BEVERAGES(TopCategory.ALCOHOLIC_BEVERAGES), WHEAT(TopCategory.CEREALS),
    CREAM(TopCategory.MILK), CONDIMENTS(TopCategory.SPICES),
    FERMENTED_MILK_PRODUCTS(TopCategory.MILK),
    SUGAR_AND_SYRUPS(TopCategory.SUGAR_AND_CONFECTIONERY),
    NON_CHOCOLATE_CONFECTIONERY(TopCategory.SUGAR_AND_CONFECTIONERY),
    SOFT_DRINKS(TopCategory.BEVERAGES), PASTA_AND_MACARONI(TopCategory.CEREALS),
    ICE_CREAM(TopCategory.MILK), RICE(TopCategory.CEREALS),
    ONION_FAMILY_VEGETABLES(TopCategory.VEGETABLES), OTHER_FAT_PRODUCTS(TopCategory.FAT),
    GAME_MEAT(TopCategory.MEAT), OATS_AND_BARLEY(TopCategory.CEREALS),
    SPIRITS(TopCategory.ALCOHOLIC_BEVERAGES), STARCHES(TopCategory.CEREALS), LAMB(TopCategory.MEAT),
    PRODUCTS_FOR_NUTRITIONAL_SUPPORT(TopCategory.PRODUCTS_FOR_SPECIAL_NUTRITION),
    MARGARINE_FAT_SPREAD_OVER_55(TopCategory.FAT), MARGARINE_FAT_SPREAD_UNDER_55(TopCategory.FAT),
    BUTTER_AND_BUTTER_SPREADS(TopCategory.FAT), WATER(TopCategory.BEVERAGES),
    RYE(TopCategory.CEREALS), OTHER_MILK_PRODUCTS(TopCategory.MILK),
    OTHER_SUGAR_PRODUCTS(TopCategory.SUGAR_AND_CONFECTIONERY),
    BEER(TopCategory.ALCOHOLIC_BEVERAGES), DRIED_SPICES(TopCategory.SPICES),
    POTATO_PRODUCTS(TopCategory.POTATOES), POTATOES(TopCategory.POTATOES),
    WINE(TopCategory.ALCOHOLIC_BEVERAGES), SALT(TopCategory.OTHER_INGREDIENTS),
    CRISPBREADS(TopCategory.CEREALS), SOYA_PRODUCTS(TopCategory.PULSES_AND_NUTS),
    SWEETENERS(TopCategory.OTHER_INGREDIENTS), ANIMAL_FATS(TopCategory.FAT),
    TEA(TopCategory.BEVERAGES), SNACKS(TopCategory.MANUFACTURED_FOODS), OTHER_EGGS(TopCategory.EGG),
    CHICKEN_EGGS(TopCategory.EGG);

    private final TopCategory topCategory;

    Category(TopCategory topCategory) {
        this.topCategory = topCategory;
    }

    public enum TopCategory {
        FRUITS, VEGETABLES, PULSES_AND_NUTS, POTATOES, CEREALS, MILK, FAT, EGG, FISH, MEAT,
        BEVERAGES, ALCOHOLIC_BEVERAGES, SUGAR_AND_CONFECTIONERY, SPICES, OTHER_INGREDIENTS,
        MANUFACTURED_FOODS, PRODUCTS_FOR_SPECIAL_NUTRITION
    }
}
