INSERT INTO FoodGroups (name, langual_code) VALUES ('Extra hårdost', 'A0310');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Hårdost', 'A0311');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Halvhård ost', 'A0312');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Mjukost', 'A0314');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Mejeriprodukter', 'A0778');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Mjölk', 'A0780');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Övriga mjölkprodukter', 'A0781');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Grädde', 'A0782');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Fil och yoghurt', 'A0783');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Färskost', 'A0786');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Övriga ostprodukter', 'A0787');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Vegetabiliska produkter', 'A0788');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Glass och annan frusen dessert', 'A0789');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Ägg', 'A0791');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Äggrätter', 'A0792');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Kött', 'A0793');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Kött', 'A0794');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Fågel', 'A0795');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Innanmat och inälvsmat', 'A0796');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Konserverat kött', 'A0797');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Korv eller liknande produkt', 'A0798');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Kötträtt', 'A0799');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Vegetariska produkter', 'A0800');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Fisk och skaldjur', 'A0801');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Fisk', 'A0802');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Fisk- och skaldjursprodukt', 'A0803');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Fisk- och skaldjursrätt', 'A0804');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Vegetabiliskt fett och olja', 'A0806');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Margarin och blandade fetter', 'A0807');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Smör', 'A0809');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Andra djurfetter', 'A0810');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Spannmål och spannmålsprodukter', 'A0812');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Mjöl eller stärkelse', 'A0813');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Ris eller annat spannmål', 'A0814');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Pasta', 'A0815');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Frukostflingor', 'A0816');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Mjukt och hårt bröd', 'A0818');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Ojäst bröd', 'A0819');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Övriga bröd', 'A0820');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Bageriprodukter, söta och/eller feta', 'A0821');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Cerealierätter t.ex. klimp, risotto, pi', 'A0822');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Nöt, frö eller kärna', 'A0823');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Nöt eller frö produkt', 'A0824');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Grönsaker, rotfrukter och svamp', 'A0825');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Grönsaker och svamp', 'A0826');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Grönsaksprodukter', 'A0827');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Grönsaksrätter', 'A0828');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Potatis och rotfrukter', 'A0829');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Potatisrätter', 'A0830');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Baljväxter', 'A0831');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Baljväxträtter', 'A0832');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Frukt och bär', 'A0833');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Konserverad frukt och bär', 'A0834');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Socker och söta livsmedel', 'A0835');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Socker, honung eller sirap', 'A0836');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Sylt eller marmelad', 'A0837');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Konfekt och annan sockerprodukt dvs ej c', 'A0838');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Choklad eller chokladprodukt', 'A0839');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Juice och nektar', 'A0841');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Dryck utan alkohol', 'A0842');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Läsk', 'A0843');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Vatten', 'A0844');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Kaffe, te och kakao', 'A0845');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Öl eller maltdryck', 'A0847');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Cider och liknande drycker', 'A0848');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Vin och vinliknande drycker', 'A0849');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Likör eller sprit', 'A0850');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Kryddor smaksättare dressing röror', 'A0853');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Baknings ingrediens', 'A0854');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Kryddning eller extrakt', 'A0856');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Krydda', 'A0857');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Smaksättare, tex ketchup, sojasås, senap', 'A0858');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Dressing, majonnäs', 'A0859');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Chutney eller pickle', 'A0860');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Maträtter och efterrätter', 'A0861');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Sås', 'A0862');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Dessertsås', 'A0863');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Dessert', 'A0864');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Soppa', 'A0865');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Färdigsallad', 'A0866');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Snacks', 'A0868');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Övriga livsmedel', 'A0869');
INSERT INTO FoodGroups (name, langual_code) VALUES ('Kosttillskott och hälsopreparat', 'A0870');
