INSERT INTO Parts (name, langual_code) VALUES ('Inte tillämpligt', NULL);
INSERT INTO Parts (name, langual_code) VALUES ('Del av växt eller djur inte känt', 'C0001');
INSERT INTO Parts (name, langual_code) VALUES ('Stam', 'C0101');
INSERT INTO Parts (name, langual_code) VALUES ('Kött del', 'C0103');
INSERT INTO Parts (name, langual_code) VALUES ('Mjölk el mjölkkomponent', 'C0113');
INSERT INTO Parts (name, langual_code) VALUES ('Grädde el gräddkomponent', 'C0123');
INSERT INTO Parts (name, langual_code) VALUES ('Skelett kött del, utan ben eller skal', 'C0125');
INSERT INTO Parts (name, langual_code) VALUES ('Frö eller kärna, skal borttaget, grodd kvar', 'C0132');
INSERT INTO Parts (name, langual_code) VALUES ('Fullkorn, hela frön, gryn, bönor', 'C0133');
INSERT INTO Parts (name, langual_code) VALUES ('Frö eller kärna, skal borttaget', 'C0134');
INSERT INTO Parts (name, langual_code) VALUES ('Frö eller kärna, skal kvar', 'C0135');
INSERT INTO Parts (name, langual_code) VALUES ('Frukt eller bär, skal borttaget', 'C0138');
INSERT INTO Parts (name, langual_code) VALUES ('Frukt eller bär, oskalad, kärna eller frö borttaget', 'C0139');
INSERT INTO Parts (name, langual_code) VALUES ('Frukt eller bär, oskalad, kärna kvar', 'C0140');
INSERT INTO Parts (name, langual_code) VALUES ('Växter ovanför ytan, inte frukt och frön', 'C0144');
INSERT INTO Parts (name, langual_code) VALUES ('Hel växt eller de mesta delarna används', 'C0150');
INSERT INTO Parts (name, langual_code) VALUES ('Huvudväxt', 'C0151');
INSERT INTO Parts (name, langual_code) VALUES ('Frö eller kärna', 'C0155');
INSERT INTO Parts (name, langual_code) VALUES ('Brunt socker', 'C0156');
INSERT INTO Parts (name, langual_code) VALUES ('Vitt socker', 'C0157');
INSERT INTO Parts (name, langual_code) VALUES ('Balja eller frö', 'C0158');
INSERT INTO Parts (name, langual_code) VALUES ('Lätt grädde - mjölkfett 18%-30%', 'C0160');
INSERT INTO Parts (name, langual_code) VALUES ('Fet grädde - mjölkfett 36%>', 'C0161');
INSERT INTO Parts (name, langual_code) VALUES ('Frukt eller bär', 'C0167');
INSERT INTO Parts (name, langual_code) VALUES ('Balja med små omogna fröer tex gröna bönor', 'C0169');
INSERT INTO Parts (name, langual_code) VALUES ('Hela djuret eller de flesta delarna används', 'C0173');
INSERT INTO Parts (name, langual_code) VALUES ('Del av växt', 'C0174');
INSERT INTO Parts (name, langual_code) VALUES ('Skelett kött del', 'C0175');
INSERT INTO Parts (name, langual_code) VALUES ('Lever', 'C0176');
INSERT INTO Parts (name, langual_code) VALUES ('Smör - grädde 80%>', 'C0179');
INSERT INTO Parts (name, langual_code) VALUES ('Groddar', 'C0183');
INSERT INTO Parts (name, langual_code) VALUES ('Blod', 'C0185');
INSERT INTO Parts (name, langual_code) VALUES ('Stjälk', 'C0186');
INSERT INTO Parts (name, langual_code) VALUES ('Honung', 'C0188');
INSERT INTO Parts (name, langual_code) VALUES ('Tunga', 'C0189');
INSERT INTO Parts (name, langual_code) VALUES ('Fett eller olja', 'C0190');
INSERT INTO Parts (name, langual_code) VALUES ('Grädde - mjölkfett 18%>', 'C0195');
INSERT INTO Parts (name, langual_code) VALUES ('Njure', 'C0196');
INSERT INTO Parts (name, langual_code) VALUES ('Blad', 'C0200');
INSERT INTO Parts (name, langual_code) VALUES ('Hjärta', 'C0201');
INSERT INTO Parts (name, langual_code) VALUES ('Rom', 'C0202');
INSERT INTO Parts (name, langual_code) VALUES ('Stärkelse', 'C0203');
INSERT INTO Parts (name, langual_code) VALUES ('Melass', 'C0207');
INSERT INTO Parts (name, langual_code) VALUES ('Sackaros', 'C0210');
INSERT INTO Parts (name, langual_code) VALUES ('Mage', 'C0211');
INSERT INTO Parts (name, langual_code) VALUES ('Äggula', 'C0215');
INSERT INTO Parts (name, langual_code) VALUES ('Gelatin', 'C0219');
INSERT INTO Parts (name, langual_code) VALUES ('Fruktos', 'C0223');
INSERT INTO Parts (name, langual_code) VALUES ('Helt ägg utan skal', 'C0225');
INSERT INTO Parts (name, langual_code) VALUES ('Frö och nötter i skal', 'C0227');
INSERT INTO Parts (name, langual_code) VALUES ('Frukt eller bär, skal borttaget, kärna eller frö borttaget', 'C0229');
INSERT INTO Parts (name, langual_code) VALUES ('Frukt eller bär, skal borttaget, kärna eller frö kvar', 'C0230');
INSERT INTO Parts (name, langual_code) VALUES ('Mjölk', 'C0235');
INSERT INTO Parts (name, langual_code) VALUES ('Protein extrakt, konstrat eller isolat', 'C0236');
INSERT INTO Parts (name, langual_code) VALUES ('Blomma', 'C0237');
INSERT INTO Parts (name, langual_code) VALUES ('Rötter, knölar och lökar', 'C0238');
INSERT INTO Parts (name, langual_code) VALUES ('Äggvita', 'C0241');
INSERT INTO Parts (name, langual_code) VALUES ('Frö på pinne t ex majskolv', 'C0242');
INSERT INTO Parts (name, langual_code) VALUES ('Vassle', 'C0244');
INSERT INTO Parts (name, langual_code) VALUES ('Ostmassa', 'C0245');
INSERT INTO Parts (name, langual_code) VALUES ('Del av alg eller svamp', 'C0247');
INSERT INTO Parts (name, langual_code) VALUES ('Ärtor i skida, balja med fröer', 'C0262');
INSERT INTO Parts (name, langual_code) VALUES ('skelett kött del, med ben och med skinn', 'C0265');
INSERT INTO Parts (name, langual_code) VALUES ('skelett kött del, med ben och utan skinn', 'C0266');
INSERT INTO Parts (name, langual_code) VALUES ('Skelett kött del, utan ben med skinn', 'C0267');
INSERT INTO Parts (name, langual_code) VALUES ('Skelett kött del, utan ben och utan skinn', 'C0268');
INSERT INTO Parts (name, langual_code) VALUES ('Skelett kött del, utan ben och utan skinn med separerbart fett', 'C0269');
INSERT INTO Parts (name, langual_code) VALUES ('Skelett kött del, utan ben och utan skinn, utan separerbart fett', 'C0270');
INSERT INTO Parts (name, langual_code) VALUES ('Socker sirap och flytande sirap', 'C0271');
INSERT INTO Parts (name, langual_code) VALUES ('Bräss', 'C0273');
INSERT INTO Parts (name, langual_code) VALUES ('Helt ägg', 'C0274');
INSERT INTO Parts (name, langual_code) VALUES ('Kli', 'C0288');
INSERT INTO Parts (name, langual_code) VALUES ('Lök', 'C0290');
INSERT INTO Parts (name, langual_code) VALUES ('Kärna', 'C0293');
INSERT INTO Parts (name, langual_code) VALUES ('Skal', 'C0294');
INSERT INTO Parts (name, langual_code) VALUES ('Olja från groddar', 'C0297');
INSERT INTO Parts (name, langual_code) VALUES ('Juice', 'C0300');
INSERT INTO Parts (name, langual_code) VALUES ('Olja från skal', 'C0302');
INSERT INTO Parts (name, langual_code) VALUES ('Rot', 'C0306');
INSERT INTO Parts (name, langual_code) VALUES ('Olja från frön', 'C0307');
INSERT INTO Parts (name, langual_code) VALUES ('Knöl', 'C0308');
INSERT INTO Parts (name, langual_code) VALUES ('Mjöl, grodd och kli borttaget (Endosperm)', 'C0208');
INSERT INTO Parts (name, langual_code) VALUES ('Del av växt eller djur inte applicerbart (kemiskt ämne)', 'C0005');
